### ISSUE TITLE
Refactor constraint checking and enable meta rule checking separately.

### ISSUE THREAD

**Issue by pmeijer** [webgme/webgme#543]
- [x] Move the meta rules to a separate function.
- [x] Make a constraint checker class for evaluation constraints (custom and the meta-rules).
- [x] Add separate entry point on GUI and worker for evaluating Meta-rules.
- [x] Check custom constraints w/o using AddOn.
